name: Generate CycloneDX SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      repository-url:
        description: "Optional: The URL of the repository to generate SBOM for (e.g., 'https://github.com/Wa1idMahmoud/sbom-gha-gen')"
        required: false
        default: ""

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository-url || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft packages dir:. -o cyclonedx-json=./sbom.json

      - name: Upload SBOM as Artefact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: sbom
          path: ./sbom.json

      - name: Upload SBOM to Dependency-Track
        uses: DependencyTrack/gh-upload-sbom@v2.0.0
        with:
          serverHostname: "http://localhost:8080"
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          project: "CTP-Team"
