name: Generate CycloneDX SBOM

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      repository-url:
        description: "Optional: The URL of the repository to generate SBOM for (e.g., https://github.com/Wa1idMahmoud/sbom-gha-gen)"
        required: false
        default: ""

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft packages dir:. -o cyclonedx-json=./sbom.json

      - name: Upload SBOM as Artefact
        uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: ./sbom.json
