name: Generate SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM
      run: |
        syft packages dir:/path/to/project -o cyclonedx-json=sbom.json

    - name: Upload SBOM as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sbom-artifact
        path: sbom.json
