name: Generate, Artifact SBOM

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      repository-url:
        description: 'Optional: The URL of the repository to generate SBOM for (e.g., https://github.com/Wa1idMahmoud/sbom-gha-gen)'
        required: false
        default: ''

jobs:
  sbom:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository-url || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Anchore SBOM Action
        uses: anchore/sbom-action@v0.15.8
        with:
          # Optionally, you can specify output file, format, etc.
          path: "." # Scans the root directory of the repository

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: buildOutput


